Implement a REST api
rubeljmarta/SummerSchool pull request #3
Opened 2021-08-10 16:45 UTC by rubeljmarta

Pizzas, details of the current pizzeria, customer details, new customer registration, updating and deleting customers are displayed. ExceptionHandler added. Delivery does not work.

2021-08-11 09:51 UTC, mariobutir commented on src/main/java/com/agency04/sbss/pizza/rest/Controller.java
> +    }
Bolje koristi `GetMapping`, `PutMapping`, `PostMapping` i `DeleteMapping` anotacije umisto `RequestMapping,` ovisno sta ti triba

2021-08-11 09:57 UTC, mariobutir requested changes
Evo ostavljen komentar u vezi controllera

2021-08-13 10:13 UTC, antoniosostar requested changes

2021-08-13 10:13 UTC, antoniosostar commented on src/main/java/com/agency04/sbss/pizza/rest/CustomerController.java
> +    public List<Customer> all_customer(){
Koristi CamelCase za nazive metoda (e.g. allCustomers).

2021-08-13 10:13 UTC, antoniosostar commented on src/main/java/com/agency04/sbss/pizza/service/impl/CustomerServiceImpl.java
> +    ));
Bilo bi dobro imati inicijalizaciju podataka na jednom mjestu - pa skupiti sve u jedno PostConstruct metodu...

2021-08-13 10:13 UTC, antoniosostar commented on src/main/java/com/agency04/sbss/pizza/service/impl/PizzaDelivery.java
> +        ){
Ovdje bi bilo bolje iskoristiti PizzaMenu objekt (kojeg bih ja osobno napravio kao Bean) da se izbjegne hardkodiranje.

2021-08-17 14:49 UTC, merged